FROM python:3.11-slim

WORKDIR /llm_app

COPY requirements.txt ./llm_app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r ./llm_app/requirements.txt

COPY . .

ARG LLM_PORT=8011
ENV LLM_PORT=$LLM_PORT

CMD ["sh", "-c", "uvicorn llm_app/main:app --host 0.0.0.0 --port $LLM_PORT"]
