FROM python:3.12-slim

WORKDIR /llm_app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . ./llm_app

ARG LLM_PORT=8011
ENV LLM_PORT=$LLM_PORT

CMD ["sh", "-c", "uvicorn llm_app.main:llm_app --host 0.0.0.0 --port $LLM_PORT"]
