FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r ./app/requirements.txt

COPY . .

ARG API_PORT=8000
ENV API_PORT=$API_PORT

CMD ["sh", "-c", "uvicorn app/main:app --host 0.0.0.0 --port $API_PORT"]