FROM python:3.11-slim

WORKDIR /qdrant_app

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

ARG VECT_QD_PORT=8008
ENV VECT_QD_PORT=$VECT_QD_PORT

CMD ["sh", "-c", "uvicorn qdrant_app.main:app --host 0.0.0.0 --port $VECT_QD_PORT"]
